language: java

jdk:
  - oraclejdk8

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "DEDdIg/UNl7mANk6+0JiqDH+ESUeyExi8NLoUI9aWOj8KR06bBQOLTdQGNgXdiDQdWbtcRtyVFEAEgiIeXDPknIJBIRtagBLUcutYRgrb9qMriMxB7a3AEl8DRlAsWrnsQIY2KwZF0yimh5yqLrqk+gFXAB1fsth51cDIQpIUjAUcW2S0mAUB+kYFIoB/zEnxuvqpeuwahe8BvfmMXkoeXVYSmphk61KkAOj83GNXPcXUqFDdnxbHbKRuC7cHwOzQKEHjOpyVlnzNc/+91goSlFQgCM2X3zABv/HwPwKvVALWR6Iw2kVMv7D0Z8kV0rEen+BTlaydOFtzl8qwFrHn11Z2ormIOcAa17+vu6C6FUAyJ0B+vXdjiLBtWjlrirR7NvD32bMKKL5060g0wDXbBRtmHJ6IQ/WQcfY3+c6mFMEv2eoBn9XDdcRGUP4Wljjyh3S48kMu/co4SRkDB8re277zkQ+ZDb0rA7Htvr1gDqNnwETFEmhRolOy4FAvAipZIsw7ISQmwg1C47H2sKMkiT2l7GKZ8pIwQIAjAgT+iLkrfhXb4X7F8Umbu7m3unTZwgM2B2jJb/hzffq941b0VwOKYb8qYCSnR7wJ+8ZA/oDtiwKNuLPXZHJ1L13irBWOSO8Ya7MbaivOU2qqry8D9qzrkETDwt8nrqe3cYkuD0="
    - secure: "sOrWIRShYGtwD5Nf01eGDHW+/p4HodEw//dItBp7HN1nqdcDwxuAprEy/SNhdJjSXhIHLESpbTKmvrZ41rezHP6XfgJApab1itgOPLlkUD71yLccKbPLa6hYvEQyL6UnGBtLucwNV2GTxzsxYcYdEdu9mmGUx1bWHU93I00Ds3M/vF/TrvLfyh/0bO7Y9LVOCFPscMBVgshrvx0Z5Cl+bJIgGaM6Jh6qrx2sWi+q4CHvUeAzcibxxxDFLtAFj/SnCKLWbEbwRiaP8a8egW5OE1HLfLZrBX9PxkZ+Hj7TqVI+X6XfwVVFfBI9ZL8Fc94177WKRPuwMnwvvEe7FvwEft+w6nbQaNNyJe97ZeP7B7ToMUitrtLC3E7EMiLCYHlp+hqYQZ10h4Nnl3O/5tPWU9MKG+6CsbJkO9FPiwo1L/7EtVuJcAGv0bOqxVu24fuAMUe22egZp8hzuwAZmY5OFFRbgpB+14vGFvXwjY4+ROXkTkfFWnTSFdiKj49+pwKYXa/5NEIVgqRq87Z528NQCb1SdPXabJq65QMNyFq7YOVBz1nd0NbHSIiCKf6Z3H0DTz2r7fnMZRFrhasjOEot53D3VKnYLLqn1pnshfi6ITRZ6yadlFzX+mT/MnsEQF+NB2AynIkhtTNW+mV/bm3aFC+bXd3tIAPZmXQV4bjpDvE="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
